import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openProductPersistence} from '../shared/packages/vertical-persistence/src/index.js';
import {createPastureManagementService} from '../src/services/pasture-management.js';

async function fixture(){const dir=await mkdtemp(join(tmpdir(),'pecuaria-pasture-'));const db=await openProductPersistence({dbPath:join(dir,'db.sqlite'),productId:'agro-pecuaria'});return{dir,db,service:createPastureManagementService(db),async close(){await db.close();await rm(dir,{recursive:true,force:true})}}}
async function seed(f){await f.db.putRecord('cattle.lots','lot-1',{id:'lot-1',name:'Lote 1',farmUnitId:'farm-1',purpose:'beef',metadata:{}},{expectedVersion:0});await f.db.putRecord('cattle.lots','lot-2',{id:'lot-2',name:'Lote 2',farmUnitId:'farm-1',purpose:'beef',metadata:{}},{expectedVersion:0});await f.db.putRecord('cattle.animals','a1',{id:'a1',tag:'A1',farmUnitId:'farm-1',lotId:'lot-1',sex:'female',status:'active',weights:[],milkRecords:[],movements:[],lifecycle:[],metadata:{}},{expectedVersion:0});}

test('pasture service records assessment body score and rotation plan',async()=>{const f=await fixture();try{await seed(f);await f.service.savePasture({id:'p1',name:'Piquete',farmUnitId:'farm-1',areaHa:10,capacityAu:20,restTargetDays:20});const assessment=await f.service.recordAssessment({id:'pa1',pastureId:'p1',occurredAt:'2026-09-20',score:4,heightCm:30});assert.equal(assessment.score,4);const body=await f.service.recordBodyCondition({id:'bc1',animalId:'a1',occurredAt:'2026-09-20',score:3.5});assert.equal(body.score,3.5);const plan=await f.service.saveRotationPlan({id:'rp1',pastureId:'p1',lotId:'lot-1',plannedEnterAt:'2026-09-21',plannedLeaveAt:'2026-09-24'});assert.equal(plan.status,'planned');}finally{await f.close()}});

test('one lot cannot occupy two pastures simultaneously and enter/leave is transactional',async()=>{const f=await fixture();try{await seed(f);await f.service.savePasture({id:'p1',name:'P1',farmUnitId:'farm-1',areaHa:10});await f.service.savePasture({id:'p2',name:'P2',farmUnitId:'farm-1',areaHa:8});await f.service.enterLot({id:'occ1',pastureId:'p1',lotId:'lot-1',enteredAt:'2026-09-20T08:00:00Z',animalUnits:8});await assert.rejects(()=>f.service.enterLot({id:'occ2',pastureId:'p2',lotId:'lot-1',enteredAt:'2026-09-20T09:00:00Z',animalUnits:8}),/already|active|occup/i);assert.equal((await f.db.listRecords('cattle.pasture-occupancy')).length,1);await f.service.leaveLot({id:'occ1',leftAt:'2026-09-22T08:00:00Z'});const occ=(await f.db.getRecord('cattle.pasture-occupancy','occ1')).payload;assert.ok(occ.leftAt);}finally{await f.close()}});

test('operational state derives occupied resting and available without rewriting manual unavailable',async()=>{const f=await fixture();try{await seed(f);await f.service.savePasture({id:'p1',name:'P1',farmUnitId:'farm-1',areaHa:10,restTargetDays:10});await f.service.enterLot({id:'occ1',pastureId:'p1',lotId:'lot-1',enteredAt:'2026-09-01',animalUnits:5});let snap=await f.service.snapshot({now:'2026-09-05T00:00:00Z'});assert.equal(snap.pastures[0].operationalStatus,'occupied');await f.service.leaveLot({id:'occ1',leftAt:'2026-09-10'});snap=await f.service.snapshot({now:'2026-09-15T00:00:00Z'});assert.equal(snap.pastures[0].operationalStatus,'resting');snap=await f.service.snapshot({now:'2026-09-25T00:00:00Z'});assert.equal(snap.pastures[0].operationalStatus,'available');await f.service.savePasture({id:'p1',name:'P1',farmUnitId:'farm-1',areaHa:10,restTargetDays:10,status:'unavailable'});snap=await f.service.snapshot({now:'2026-09-25T00:00:00Z'});assert.equal(snap.pastures[0].operationalStatus,'unavailable');}finally{await f.close()}});
