import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ACTION_FORMS} from '../web/action-config.js';

const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');

test('finance inputs are presented in reais and normalized to integer minor units',()=>{
  const trade=ACTION_FORMS.trades.create;
  const amount=trade.fields.find(field=>field.name==='totalAmountMinor');
  const arroba=trade.fields.find(field=>field.name==='pricePerCarcassArrobaMinor');
  assert.equal(amount.label,'Valor total/líquido (R$)');
  assert.equal(amount.moneyMinor,true);
  assert.equal(arroba.label,'Preço por @ de carcaça (R$)');
  assert.equal(arroba.moneyMinor,true);
  const normalized=trade.normalize({id:'t1',type:'sale',partyId:'p1',animalIds:['a1'],totalAmountMinor:'R$ 1.234,56',pricePerCarcassArrobaMinor:'287,50',occurredAt:'2026-09-21T10:00'});
  assert.equal(normalized.totalAmountMinor,123456);
  assert.equal(normalized.pricePerCarcassArrobaMinor,28750);

  const title=ACTION_FORMS.finance.saveTitle;
  assert.equal(title.fields.find(field=>field.name==='originalAmountMinor').label,'Valor (R$)');
  assert.equal(title.normalize({direction:'payable',description:'Ração',originalAmountMinor:'2.500,00',issuedAt:'2026-09-21',dueAt:'2026-09-30'}).originalAmountMinor,250000);
});

test('technical finance ids are generated by normalizers instead of requested from the operator',()=>{
  for(const action of ['saveTitle','settleTitle','reverseSettlement']){
    const names=ACTION_FORMS.finance[action].fields.map(field=>field.name);
    assert.ok(!names.includes('operationId'),`${action} still exposes operationId`);
  }
  assert.ok(!ACTION_FORMS.finance.saveTitle.fields.some(field=>field.name==='id'));
  assert.ok(!ACTION_FORMS.finance.settleTitle.fields.some(field=>field.name==='id'));
  assert.ok(!ACTION_FORMS.finance.reverseSettlement.fields.some(field=>field.name==='id'));

  const title=ACTION_FORMS.finance.saveTitle.normalize({direction:'payable',description:'Frete',originalAmountMinor:'350,00',issuedAt:'2026-09-21',dueAt:'2026-09-22'});
  assert.match(title.id,/^title-/);
  const settlement=ACTION_FORMS.finance.settleTitle.normalize({titleId:'title-x',amountMinor:'120,00',occurredAt:'2026-09-21T10:00'});
  assert.match(settlement.id,/^settlement-/);
  assert.match(settlement.operationId,/^settlement-op-/);
});

test('workspace buttons use Portuguese action form titles and domain table adds local usability',async()=>{
  const components=await read('web/components.jsx');
  const main=await read('web/main.jsx');
  assert.match(components,/actionForms\?\.\[name\]\?\.title/);
  assert.match(main,/actionForms=\{ACTION_FORMS\[screenId\]/);
  assert.match(components,/data-testid="domain-table-search"/);
  assert.match(components,/data-testid="domain-table-sort"/);
});

test('finance workspace exposes contextual title settlement reversal and reconciliation actions',async()=>{
  const source=await read('web/finance-admin.jsx');
  for(const testId of ['finance-context-settle','finance-context-cancel','finance-context-reverse','finance-context-reconcile'])assert.match(source,new RegExp(`data-testid="${testId}`));
  assert.match(source,/Valor \(R\$\)/);
  assert.ok(!source.includes('ID da operação'));
});

test('navigation and workspace copy reflect the deeper product surface',async()=>{
  const ui=await read('src/ui.js');
  const components=await read('web/components.jsx');
  assert.match(ui,/id:'finance',label:'Financeiro'/);
  assert.match(ui,/id:'tasks',label:'Manejo & Campo'/);
  for(const id of ['traceability','inventory','pastures','nutrition','tasks'])assert.match(components,new RegExp(`${id}:'`));
});

test('product status reflects that P1 is already merged on main',async()=>{
  const status=await read('PRODUCT_STATUS.md');
  assert.ok(!status.includes('antes do merge em `main`'));
  assert.match(status,/integrados? (?:ao|no) `main`/i);
});
