import assert from 'node:assert/strict';
import {copyFile,mkdtemp,mkdir,readFile,rm,stat,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {createStandaloneHost} from '../runtime/host.mjs';
const contract=JSON.parse(await readFile(new URL('../qa/product-contract.json',import.meta.url),'utf8'));
const artifacts=fileURLToPath(new URL('../qa-artifacts/',import.meta.url));
const summaryPath=join(artifacts,'phase6-compatibility.json');
const requireLegacy=process.argv.includes('--require-legacy'),arg=process.argv.find(v=>v.startsWith('--legacy-db=')),legacyDb=arg?.slice('--legacy-db='.length)||process.env.ARTISYS_LEGACY_DB||null;
const line=(s,l,d='')=>process.stdout.write(`[${s}] ${l}${d?` - ${d}`:''}\n`);let root,host,db;const summary={phase:6,productId:contract.productId,status:'failed',legacyDatabase:Boolean(legacyDb),checks:{}};
try{await mkdir(artifacts,{recursive:true});for(const expected of contract.persistence){const actual=JSON.parse(await readFile(new URL(`../${expected.file}`,import.meta.url),'utf8'));assert.equal(actual.productId,expected.productId);assert.equal(actual.databaseFile,expected.databaseFile);assert.equal(actual.migrationNamespace,expected.migrationNamespace)}summary.checks.staticPersistenceContract=true;line('PASS','Contrato de persistência');if(requireLegacy&&!legacyDb)throw new Error('ARTISYS_LEGACY_DB é obrigatório para o cutover legado.');root=await mkdtemp(join(tmpdir(),`${contract.productId}-phase6-`));const dbPath=join(root,contract.databaseFile);if(legacyDb){await stat(legacyDb);await copyFile(legacyDb,dbPath);line('PASS','Banco legado copiado para sandbox',legacyDb)}host=await createStandaloneHost({dataDir:root});const meta=await host.backend.describe();assert.equal(meta.productId,contract.productId);assert.deepEqual(meta.navigation.map(x=>x.id),contract.screens);assert.equal((await host.persistence.health()).ok,true);summary.checks.runtimeOpen=true;line('PASS','Abertura standalone');await host.close();host=null;db=new DatabaseSync(dbPath,{readOnly:true});const owner=db.prepare("SELECT value FROM __artisys_meta WHERE key='product_id'").get();assert.equal(owner?.value,contract.productId);const migrations=db.prepare('SELECT id FROM __artisys_migrations ORDER BY id').all().map(x=>x.id);for(const id of contract.migrationIds)assert.ok(migrations.includes(id),`migration ausente: ${id}`);summary.checks.databaseOwnership=true;summary.checks.migrations=true;summary.migrations=migrations;summary.status='passed';summary.finishedAt=new Date().toISOString();await writeFile(summaryPath,JSON.stringify(summary,null,2)+'\n');line('PASS','FASE 6',legacyDb?'compatibilidade com banco legado validada':'contrato e banco novo validados')}catch(error){summary.error=error.stack??error.message;summary.finishedAt=new Date().toISOString();await mkdir(artifacts,{recursive:true}).catch(()=>{});await writeFile(summaryPath,JSON.stringify(summary,null,2)+'\n').catch(()=>{});line('FAIL','FASE 6',error.message);process.exitCode=1}finally{try{db?.close()}catch{}await host?.close?.().catch(()=>{});if(root&&process.env.ARTISYS_QA_KEEP!=='1')await rm(root,{recursive:true,force:true}).catch(()=>{})}
