const clean=v=>typeof v==='string'?v.trim():v;
const num=v=>v===''||v==null?undefined:Number(v);
const list=v=>Array.isArray(v)?v.map(clean).filter(Boolean):String(v??'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean);
const dateTime=v=>v?new Date(v).toISOString():undefined;
const field=(name,label,type='text',extra={})=>Object.freeze({name,label,type,...extra});
const form=(title,fields,normalize=(values)=>Object.fromEntries(Object.entries(values).filter(([,v])=>v!==''&&v!=null)))=>Object.freeze({title,fields:Object.freeze(fields),defaults:Object.freeze({}),normalize});
const iotProfiles=[['serial-rfid','Leitor RFID Serial/USB'],['serial-scale','Balança Serial/USB'],['mqtt-rfid','Leitor RFID MQTT'],['mqtt-scale','Balança MQTT'],['http-rfid','Leitor RFID HTTP local'],['http-scale','Balança HTTP local'],['simulator-rfid','Simulador RFID'],['simulator-scale','Simulador de balança']];
const iotDevice=v=>{
  const profileId=clean(v.profileId),base={id:clean(v.id),name:clean(v.name),profileId,stationId:clean(v.stationId)||null,farmId:clean(v.farmId)||null,enabled:String(v.enabled??'true')!=='false'};
  let config={};
  if(String(profileId).startsWith('serial-'))config={port:clean(v.port),baudRate:num(v.baudRate)??9600,...(v.delimiter!==''&&v.delimiter!=null?{delimiter:String(v.delimiter)}:{})};
  else if(String(profileId).startsWith('mqtt-'))config={url:clean(v.url),topics:list(v.topics),username:clean(v.username)||null,...(v.password?{password:v.password}:{}),...(v.token?{token:v.token}:{})};
  else if(String(profileId).startsWith('http-'))config={baseUrl:clean(v.baseUrl),path:clean(v.path)||'/',pollIntervalMs:num(v.pollIntervalMs)??1000,username:clean(v.username)||null,...(v.password?{password:v.password}:{}),...(v.token?{token:v.token}:{})};
  return{...base,config};
};
const reproductionMetadata=v=>({method:clean(v.method)||null,bullOrSemen:clean(v.bullOrSemen)||null,result:clean(v.result)||null,expectedCalvingAt:v.expectedCalvingAt?dateTime(v.expectedCalvingAt):null,notes:clean(v.notes)||null});

export const ACTION_FORMS=Object.freeze({
  lots:Object.freeze({
    save:form('Salvar lote',[field('id','ID'),field('name','Nome'),field('farmUnitId','Unidade/Fazenda','text',{refCollection:'farms'}),field('purpose','Finalidade','select',{options:[['beef','Corte'],['dairy','Leite'],['breeding','Reprodução']]})]),
    remove:form('Excluir lote',[field('id','ID do lote'),field('expectedVersion','Versão','number')],v=>({id:clean(v.id),expectedVersion:num(v.expectedVersion)}))
  }),
  animals:Object.freeze({
    save:form('Salvar animal',[field('id','ID'),field('tag','Brinco/identificação'),field('name','Nome'),field('officialId','Identificação oficial / SISBOV'),field('rfid','RFID'),field('farmUnitId','Unidade/Fazenda','text',{refCollection:'farms'}),field('lotId','Lote','text',{refCollection:'lots'}),field('breedId','Raça','text',{refCollection:'breeds'}),field('categoryId','Categoria','text',{refCollection:'categories'}),field('birthDate','Nascimento','date'),field('damId','Mãe','text',{refCollection:'animals'}),field('sireId','Pai','text',{refCollection:'animals'}),field('origin','Origem'),field('purpose','Finalidade','select',{options:[['beef','Corte'],['dairy','Leite'],['breeding','Reprodução']]}),field('sex','Sexo','select',{options:[['female','Fêmea'],['male','Macho'],['unknown','Não informado']]})]),
    batchMove:form('Mover animais em lote',[field('animalIds','Animais','list',{refCollection:'animals'}),field('toLotId','Lote destino','text',{refCollection:'lots'}),field('movedAt','Data/hora','datetime-local'),field('reason','Motivo')],v=>({animalIds:list(v.animalIds),toLotId:clean(v.toLotId),movedAt:dateTime(v.movedAt),reason:clean(v.reason)||'management'})),
    batchLifecycle:form('Baixa coletiva',[field('animalIds','Animais','list',{refCollection:'animals'}),field('type','Evento','select',{options:[['death','Morte'],['sale','Venda'],['disposal','Baixa']]}),field('occurredAt','Data/hora','datetime-local'),field('reason','Motivo')],v=>({animalIds:list(v.animalIds),type:v.type,occurredAt:dateTime(v.occurredAt),reason:clean(v.reason)||null})),
    recordMilk:form('Registrar produção de leite',[field('id','Animal','text',{refCollection:'animals'}),field('liters','Produção (litros)','number',{step:'0.1'}),field('measuredAt','Data/hora','datetime-local')],v=>({id:clean(v.id),liters:num(v.liters),measuredAt:dateTime(v.measuredAt)})),
    move:form('Mover animal',[field('id','Animal','text',{refCollection:'animals'}),field('toLotId','Lote destino','text',{refCollection:'lots'}),field('movedAt','Data/hora','datetime-local'),field('reason','Motivo')],v=>({id:clean(v.id),toLotId:clean(v.toLotId),movedAt:dateTime(v.movedAt),reason:clean(v.reason)||'management'})),
    lifecycle:form('Registrar ciclo de vida',[field('id','Animal','text',{refCollection:'animals'}),field('type','Evento','select',{options:[['birth','Nascimento'],['death','Morte'],['sale','Venda'],['disposal','Baixa']]}),field('occurredAt','Data/hora','datetime-local'),field('reason','Motivo')],v=>({id:clean(v.id),type:v.type,occurredAt:dateTime(v.occurredAt),reason:clean(v.reason)||null}))
  }),
  weights:Object.freeze({record:form('Registrar pesagem',[field('id','Animal','text',{refCollection:'animals'}),field('weightKg','Peso (kg)','number',{step:'0.1'}),field('measuredAt','Data/hora','datetime-local')],v=>({id:clean(v.id),weightKg:num(v.weightKg),measuredAt:dateTime(v.measuredAt)}))}),
  sanitary:Object.freeze({
    saveProtocol:form('Salvar protocolo sanitário',[field('id','ID'),field('name','Nome'),field('productItemId','Produto/insumo','text',{refCollection:'inventory'}),field('activeIngredient','Princípio ativo'),field('dose','Dose','number',{step:'0.01'}),field('unit','Unidade'),field('intervalDays','Intervalo entre doses (dias)','number'),field('withdrawalDays','Carência (dias)','number')],v=>({id:clean(v.id),name:clean(v.name),productItemId:clean(v.productItemId),activeIngredient:clean(v.activeIngredient)||null,dose:num(v.dose),unit:clean(v.unit),intervalDays:num(v.intervalDays)??null,withdrawalDays:num(v.withdrawalDays)??null})),
    batchRecord:form('Aplicação sanitária coletiva',[field('animalIds','Animais','list',{refCollection:'animals'}),field('protocolId','Protocolo','text',{refCollection:'protocols'}),field('productItemId','Produto/insumo','text',{refCollection:'inventory'}),field('dose','Dose','number',{step:'0.01'}),field('unit','Unidade'),field('occurredAt','Aplicação','datetime-local'),field('nextDueAt','Próxima dose','datetime-local'),field('withdrawalUntil','Fim da carência','datetime-local'),field('technicianPartyId','Responsável','text',{refCollection:'parties'})],v=>({animalIds:list(v.animalIds),protocolId:clean(v.protocolId)||null,productItemId:clean(v.productItemId)||undefined,dose:num(v.dose),unit:clean(v.unit)||undefined,occurredAt:dateTime(v.occurredAt),nextDueAt:v.nextDueAt?dateTime(v.nextDueAt):null,withdrawalUntil:v.withdrawalUntil?dateTime(v.withdrawalUntil):null,technicianPartyId:clean(v.technicianPartyId)||null})),
    record:form('Registrar manejo sanitário',[field('id','ID do evento'),field('animalId','Animal','text',{refCollection:'animals'}),field('protocolId','Protocolo','text',{refCollection:'protocols'}),field('productItemId','Produto/insumo','text',{refCollection:'inventory'}),field('dose','Dose','number',{step:'0.01'}),field('unit','Unidade'),field('occurredAt','Aplicação','datetime-local'),field('nextDueAt','Próxima dose','datetime-local'),field('withdrawalUntil','Fim da carência','datetime-local'),field('technicianPartyId','Responsável','text',{refCollection:'parties'})],v=>({id:clean(v.id),animalId:clean(v.animalId),protocolId:clean(v.protocolId)||null,productItemId:clean(v.productItemId)||undefined,dose:num(v.dose),unit:clean(v.unit)||undefined,occurredAt:dateTime(v.occurredAt),nextDueAt:v.nextDueAt?dateTime(v.nextDueAt):null,withdrawalUntil:v.withdrawalUntil?dateTime(v.withdrawalUntil):null,technicianPartyId:clean(v.technicianPartyId)||null}))
  }),
  reproduction:Object.freeze({
    batchRecord:form('Reprodução coletiva',[field('animalIds','Animais','list',{refCollection:'animals'}),field('type','Evento','select',{options:[['service','Cobertura/IA/IATF'],['pregnancy-check','Diagnóstico de gestação'],['pregnancy-loss','Perda gestacional'],['abortion','Aborto'],['calving','Parto'],['weaning','Desmame']]}),field('occurredAt','Data/hora','datetime-local'),field('method','Método'),field('bullOrSemen','Touro / sêmen'),field('result','Resultado'),field('expectedCalvingAt','Previsão de parto','datetime-local'),field('notes','Observações')],v=>({animalIds:list(v.animalIds),type:v.type,occurredAt:dateTime(v.occurredAt),metadata:reproductionMetadata(v)})),
    record:form('Registrar reprodução',[field('id','ID do evento'),field('animalId','Animal','text',{refCollection:'animals'}),field('type','Evento','select',{options:[['service','Cobertura/IA/IATF'],['pregnancy-check','Diagnóstico de gestação'],['pregnancy-loss','Perda gestacional'],['abortion','Aborto'],['calving','Parto'],['weaning','Desmame']]}),field('occurredAt','Data/hora','datetime-local'),field('relatedAnimalId','Animal relacionado','text',{refCollection:'animals'}),field('method','Método'),field('bullOrSemen','Touro / sêmen'),field('result','Resultado'),field('expectedCalvingAt','Previsão de parto','datetime-local'),field('notes','Observações')],v=>({id:clean(v.id),animalId:clean(v.animalId),type:v.type,occurredAt:dateTime(v.occurredAt),relatedAnimalId:clean(v.relatedAnimalId)||null,metadata:reproductionMetadata(v)}))
  }),
  trades:Object.freeze({
    create:form('Registrar negociação',[field('id','ID'),field('type','Tipo','select',{options:[['sale','Venda'],['purchase','Compra']]}),field('partyId','Cliente/fornecedor/frigorífico','text',{refCollection:'parties'}),field('animalIds','Animais','list',{refCollection:'animals'}),field('totalAmountMinor','Valor total/líquido (centavos)','number'),field('occurredAt','Data/hora','datetime-local'),field('liveWeightKg','Peso vivo total (kg)','number',{step:'0.01'}),field('carcassWeightKg','Peso de carcaça total (kg)','number',{step:'0.01'}),field('carcassYieldPct','Rendimento de carcaça (%)','number',{step:'0.01'}),field('pricePerCarcassArrobaMinor','Preço por @ de carcaça (centavos)','number'),field('deductionsMinor','Descontos (centavos)','number'),field('freightMinor','Frete (centavos)','number'),field('commissionMinor','Comissão (centavos)','number')],v=>({id:clean(v.id),type:v.type,partyId:clean(v.partyId),animalIds:list(v.animalIds),totalAmountMinor:num(v.totalAmountMinor),occurredAt:dateTime(v.occurredAt),liveWeightKg:num(v.liveWeightKg),carcassWeightKg:num(v.carcassWeightKg),carcassYieldPct:num(v.carcassYieldPct),pricePerCarcassArrobaMinor:num(v.pricePerCarcassArrobaMinor),deductionsMinor:num(v.deductionsMinor)??0,freightMinor:num(v.freightMinor)??0,commissionMinor:num(v.commissionMinor)??0}))
  }),
  finance:Object.freeze({
    addCost:form('Adicionar custo',[field('id','ID'),field('lotId','Lote','text',{refCollection:'lots'}),field('amountMinor','Valor (centavos)','number'),field('description','Descrição'),field('category','Categoria')],v=>({id:clean(v.id),lotId:clean(v.lotId),amountMinor:num(v.amountMinor),description:clean(v.description),category:clean(v.category)})),
    fromTrade:form('Gerar financeiro da negociação',[field('tradeId','ID da negociação'),field('id','ID do lançamento'),field('lotId','Lote','text',{refCollection:'lots'})]),
    saveAccount:form('Salvar conta/caixa',[field('id','ID'),field('name','Nome'),field('kind','Tipo','select',{options:[['cash','Caixa'],['bank','Conta bancária'],['other','Outra']]}),field('active','Ativa','select',{options:[['true','Sim'],['false','Não']]})],v=>({id:clean(v.id),name:clean(v.name),kind:clean(v.kind)||'cash',active:String(v.active??'true')!=='false'})),
    saveCategory:form('Salvar categoria financeira',[field('id','ID'),field('name','Nome'),field('direction','Direção','select',{options:[['both','Ambas'],['payable','A pagar'],['receivable','A receber']]}),field('active','Ativa','select',{options:[['true','Sim'],['false','Não']]})],v=>({id:clean(v.id),name:clean(v.name),direction:clean(v.direction)||'both',active:String(v.active??'true')!=='false'})),
    saveTitle:form('Salvar título',[field('id','ID'),field('direction','Tipo','select',{options:[['payable','A pagar'],['receivable','A receber']]}),field('description','Descrição'),field('originalAmountMinor','Valor (centavos)','number'),field('issuedAt','Emissão','date'),field('dueAt','Vencimento','date'),field('categoryId','Categoria'),field('accountId','Conta/caixa'),field('partyId','Parte','text',{refCollection:'parties'}),field('lotId','Lote','text',{refCollection:'lots'}),field('tradeId','Negociação'),field('documentRef','Documento'),field('notes','Observações','textarea')],v=>({id:clean(v.id),direction:v.direction,description:clean(v.description),originalAmountMinor:num(v.originalAmountMinor),issuedAt:v.issuedAt,dueAt:v.dueAt,categoryId:clean(v.categoryId)||null,accountId:clean(v.accountId)||null,partyId:clean(v.partyId)||null,lotId:clean(v.lotId)||null,tradeId:clean(v.tradeId)||null,documentRef:clean(v.documentRef)||null,notes:clean(v.notes)||null})),
    cancelTitle:form('Cancelar título',[field('id','Título'),field('cancelledAt','Data','datetime-local'),field('reason','Motivo')],v=>({id:clean(v.id),cancelledAt:dateTime(v.cancelledAt),reason:clean(v.reason)||null})),
    settleTitle:form('Baixar título',[field('id','ID da baixa'),field('operationId','ID da operação'),field('titleId','Título'),field('amountMinor','Valor (centavos)','number'),field('occurredAt','Data/hora','datetime-local'),field('accountId','Conta/caixa'),field('method','Forma'),field('notes','Observações','textarea')],v=>({id:clean(v.id),operationId:clean(v.operationId),titleId:clean(v.titleId),amountMinor:num(v.amountMinor),occurredAt:dateTime(v.occurredAt),accountId:clean(v.accountId)||null,method:clean(v.method)||null,notes:clean(v.notes)||null})),
    reverseSettlement:form('Estornar baixa',[field('id','ID do estorno'),field('operationId','ID da operação'),field('settlementId','Baixa'),field('occurredAt','Data/hora','datetime-local'),field('reason','Motivo')],v=>({id:clean(v.id),operationId:clean(v.operationId),settlementId:clean(v.settlementId),occurredAt:dateTime(v.occurredAt),reason:clean(v.reason)||null})),
    importStatement:form('Importar extrato CSV',[field('sourceName','Nome do arquivo'),field('text','Conteúdo CSV','textarea')],v=>({sourceName:clean(v.sourceName),text:String(v.text??'')})),
    reconcileStatement:form('Conciliar linha',[field('lineId','Linha importada'),field('settlementId','Baixa existente'),field('operationId','ID da operação'),field('adjustmentTitleId','Título de ajuste'),field('adjustmentSettlementId','Baixa de ajuste'),field('description','Descrição do ajuste'),field('accountId','Conta/caixa'),field('categoryId','Categoria')],v=>({lineId:clean(v.lineId),settlementId:clean(v.settlementId)||null,operationId:clean(v.operationId)||null,...(clean(v.adjustmentTitleId)?{adjustment:{titleId:clean(v.adjustmentTitleId),settlementId:clean(v.adjustmentSettlementId),description:clean(v.description)||undefined,accountId:clean(v.accountId)||null,categoryId:clean(v.categoryId)||null}}:{})})),
    importInvoiceXml:form('Ler XML/NF-e local',[field('sourceName','Nome do arquivo'),field('xml','Conteúdo XML','textarea')],v=>({sourceName:clean(v.sourceName),xml:String(v.xml??'')}))
  }),
  reports:Object.freeze({
    pdf:form('Gerar PDF',[field('type','Relatório','select',{options:[['animal-history','Histórico do animal'],['lot-kpis','Indicadores do lote'],['sanitary','Manejo sanitário'],['inventory','Estoque e insumos'],['traceability','Rastreabilidade'],['pasture','Pastagens e áreas'],['tasks','Agenda de manejo']]}),field('animalId','Animal (para histórico)','text',{refCollection:'animals'}),field('lotId','Lote (opcional)','text',{refCollection:'lots'})],v=>({type:v.type,animalId:clean(v.animalId)||undefined,lotId:clean(v.lotId)||undefined})),
    csv:form('Gerar CSV',[field('type','Relatório','select',{options:[['animal-history','Histórico do animal'],['lot-kpis','Indicadores do lote'],['sanitary','Manejo sanitário'],['inventory','Estoque e insumos'],['traceability','Rastreabilidade'],['pasture','Pastagens e áreas'],['tasks','Agenda de manejo']]}),field('animalId','Animal (para histórico)','text',{refCollection:'animals'}),field('lotId','Lote (opcional)','text',{refCollection:'lots'})],v=>({type:v.type,animalId:clean(v.animalId)||undefined,lotId:clean(v.lotId)||undefined})),
    issue:form('Emitir documento',[field('id','ID'),field('type','Tipo','select',{options:[['animal-history','Histórico do animal'],['lot-kpis','Indicadores do lote'],['sanitary','Manejo sanitário'],['inventory','Estoque e insumos'],['traceability','Rastreabilidade'],['pasture','Pastagens e áreas'],['tasks','Agenda de manejo']]}),field('format','Formato','select',{options:[['csv','CSV'],['pdf','PDF'],['json','JSON']]}),field('animalId','Animal (para histórico)','text',{refCollection:'animals'}),field('lotId','Lote (opcional)','text',{refCollection:'lots'})],v=>({id:clean(v.id),type:v.type,format:v.format,animalId:clean(v.animalId)||undefined,lotId:clean(v.lotId)||undefined}))
  }),
  traceability:Object.freeze({
    save:form('Registrar rastreabilidade',[field('id','ID'),field('animalId','Animal','text',{refCollection:'animals'}),field('officialId','Identificação oficial / SISBOV'),field('type','Tipo','select',{options:[['identity','Identificação'],['gta','GTA'],['sisbov','SISBOV'],['certificate','Certificado']]}),field('documentNumber','Número do documento'),field('issuer','Emissor'),field('issuedAt','Emissão','datetime-local'),field('expiresAt','Validade','datetime-local'),field('notes','Observações')],v=>({...v,animalId:clean(v.animalId),issuedAt:dateTime(v.issuedAt),expiresAt:v.expiresAt?dateTime(v.expiresAt):null})),
    remove:form('Excluir registro de rastreabilidade',[field('id','ID'),field('expectedVersion','Versão','number')],v=>({id:clean(v.id),expectedVersion:num(v.expectedVersion)}))
  }),
  inventory:Object.freeze({
    save:form('Cadastrar insumo',[field('id','ID'),field('name','Nome'),field('kind','Tipo','select',{options:[['medicine','Medicamento'],['vaccine','Vacina'],['supplement','Suplemento'],['feed','Alimento'],['other','Outro']]}),field('unit','Unidade'),field('quantity','Quantidade','number',{step:'0.01'}),field('minQuantity','Estoque mínimo','number',{step:'0.01'}),field('batch','Lote/partida'),field('expiresAt','Validade','datetime-local'),field('costMinor','Custo unitário (centavos)','number')],v=>({...v,quantity:num(v.quantity),minQuantity:num(v.minQuantity),costMinor:num(v.costMinor),expiresAt:v.expiresAt?dateTime(v.expiresAt):null})),
    adjust:form('Movimentar estoque',[field('id','Insumo','text',{refCollection:'inventory'}),field('delta','Entrada (+) ou saída (-)','number',{step:'0.01'}),field('occurredAt','Data/hora','datetime-local'),field('reason','Motivo'),field('unitCostMinor','Custo unitário (centavos)','number')],v=>({id:clean(v.id),delta:Number(v.delta),occurredAt:dateTime(v.occurredAt),reason:clean(v.reason)||null,unitCostMinor:v.unitCostMinor===''?null:num(v.unitCostMinor)}))
  }),
  pastures:Object.freeze({
    save:form('Cadastrar pastagem/área',[field('id','ID'),field('name','Nome'),field('farmUnitId','Fazenda','text',{refCollection:'farms'}),field('areaHa','Área (ha)','number',{step:'0.01'}),field('capacityAu','Capacidade (UA)','number',{step:'0.01'}),field('forage','Forrageira'),field('status','Status','select',{options:[['available','Disponível'],['unavailable','Indisponível']]}),field('color','Cor/identificação'),field('polygon','Polígono esquemático (x,y por linha)','textarea'),field('restTargetDays','Meta de descanso (dias)','number'),field('occupancyTargetDays','Meta de ocupação (dias)','number'),field('targetHeightCm','Altura-alvo (cm)','number',{step:'0.1'}),field('notes','Observações','textarea')],v=>({id:clean(v.id),name:clean(v.name),farmUnitId:clean(v.farmUnitId),areaHa:num(v.areaHa),capacityAu:v.capacityAu===''?null:num(v.capacityAu),forage:clean(v.forage)||null,status:clean(v.status)||'available',color:clean(v.color)||null,polygon:String(v.polygon??'').split(/\n+/).map(s=>s.trim()).filter(Boolean).map((line,index)=>{const parts=line.split(/[;, ]+/).filter(Boolean);if(parts.length!==2||!parts.every(part=>Number.isFinite(Number(part))))throw new TypeError(`Ponto ${index+1} inválido. Use x,y.`);return{x:Number(parts[0]),y:Number(parts[1])}}),restTargetDays:v.restTargetDays===''?null:num(v.restTargetDays),occupancyTargetDays:v.occupancyTargetDays===''?null:num(v.occupancyTargetDays),targetHeightCm:v.targetHeightCm===''?null:num(v.targetHeightCm),notes:clean(v.notes)||null})),
    enterLot:form('Entrada de lote na pastagem',[field('id','ID da ocupação'),field('pastureId','Pastagem','text',{refCollection:'pastures'}),field('lotId','Lote','text',{refCollection:'lots'}),field('enteredAt','Entrada','datetime-local'),field('animalUnits','Unidades animais (UA)','number',{step:'0.01'}),field('notes','Observações')],v=>({...v,enteredAt:dateTime(v.enteredAt),animalUnits:v.animalUnits===''?null:num(v.animalUnits)})),
    leaveLot:form('Saída de lote da pastagem',[field('id','ID da ocupação'),field('leftAt','Saída','datetime-local')],v=>({id:clean(v.id),leftAt:dateTime(v.leftAt)})),
    recordAssessment:form('Avaliar pastagem',[field('id','ID da avaliação'),field('pastureId','Pastagem','text',{refCollection:'pastures'}),field('occurredAt','Data/hora','datetime-local'),field('score','Escore','number',{step:'0.1'}),field('scaleMin','Escala mínima','number',{step:'0.1'}),field('scaleMax','Escala máxima','number',{step:'0.1'}),field('heightCm','Altura (cm)','number',{step:'0.1'}),field('forageMassKgHa','Massa de forragem (kg/ha)','number',{step:'0.1'}),field('groundCoverPct','Cobertura do solo (%)','number',{step:'0.1'}),field('photoPaths','Fotos locais','list'),field('notes','Observações','textarea')],v=>({id:clean(v.id),pastureId:clean(v.pastureId),occurredAt:dateTime(v.occurredAt),score:num(v.score),scaleMin:v.scaleMin===''?undefined:num(v.scaleMin),scaleMax:v.scaleMax===''?undefined:num(v.scaleMax),heightCm:v.heightCm===''?null:num(v.heightCm),forageMassKgHa:v.forageMassKgHa===''?null:num(v.forageMassKgHa),groundCoverPct:v.groundCoverPct===''?null:num(v.groundCoverPct),photoPaths:list(v.photoPaths),notes:clean(v.notes)||null})),
    recordBodyCondition:form('Registrar escore corporal',[field('id','ID da observação'),field('animalId','Animal','text',{refCollection:'animals'}),field('occurredAt','Data/hora','datetime-local'),field('score','Escore corporal','number',{step:'0.1'}),field('scaleId','Escala'),field('scaleMin','Escala mínima','number',{step:'0.1'}),field('scaleMax','Escala máxima','number',{step:'0.1'}),field('notes','Observações','textarea')],v=>({id:clean(v.id),animalId:clean(v.animalId),occurredAt:dateTime(v.occurredAt),score:num(v.score),scaleId:clean(v.scaleId)||undefined,scaleMin:v.scaleMin===''?undefined:num(v.scaleMin),scaleMax:v.scaleMax===''?undefined:num(v.scaleMax),notes:clean(v.notes)||null})),
    saveRotationPlan:form('Planejar rotação',[field('id','ID do plano'),field('pastureId','Pastagem','text',{refCollection:'pastures'}),field('lotId','Lote','text',{refCollection:'lots'}),field('plannedEnterAt','Entrada planejada','datetime-local'),field('plannedLeaveAt','Saída planejada','datetime-local'),field('status','Status','select',{options:[['planned','Planejada'],['active','Em execução'],['completed','Concluída'],['cancelled','Cancelada']]}),field('notes','Observações','textarea')],v=>({id:clean(v.id),pastureId:clean(v.pastureId),lotId:clean(v.lotId),plannedEnterAt:dateTime(v.plannedEnterAt),plannedLeaveAt:v.plannedLeaveAt?dateTime(v.plannedLeaveAt):null,status:clean(v.status)||'planned',notes:clean(v.notes)||null}))
  }),
  nutrition:Object.freeze({
    save:form('Plano nutricional',[field('id','ID'),field('name','Nome'),field('lotId','Lote','text',{refCollection:'lots'}),field('feedItemId','Insumo/alimento','text',{refCollection:'inventory'}),field('dailyKgPerHead','kg/cabeça/dia','number',{step:'0.01'}),field('startsAt','Início','datetime-local'),field('endsAt','Fim','datetime-local'),field('notes','Observações')],v=>({...v,lotId:clean(v.lotId),dailyKgPerHead:num(v.dailyKgPerHead),startsAt:dateTime(v.startsAt),endsAt:v.endsAt?dateTime(v.endsAt):null})),
    consume:form('Registrar consumo do plano',[field('planId','Plano nutricional','text',{refCollection:'nutrition'}),field('days','Dias','number'),field('occurredAt','Data/hora','datetime-local')],v=>({planId:clean(v.planId),days:num(v.days)||1,occurredAt:dateTime(v.occurredAt)}))
  }),
  tasks:Object.freeze({
    save:form('Agendar manejo',[field('id','ID'),field('title','Tarefa'),field('dueAt','Prazo','datetime-local'),field('kind','Tipo','select',{options:[['management','Manejo'],['sanitary','Sanidade'],['reproduction','Reprodução'],['weighing','Pesagem'],['pasture','Pastagem']]}),field('animalId','Animal','text',{refCollection:'animals'}),field('lotId','Lote','text',{refCollection:'lots'}),field('notes','Observações')],v=>({...v,dueAt:dateTime(v.dueAt),animalId:clean(v.animalId)||null,lotId:clean(v.lotId)||null})),
    complete:form('Concluir tarefa',[field('id','ID da tarefa')],v=>({id:clean(v.id)}))
  }),
  data:Object.freeze({
    saveFarmUnit:form('Cadastrar fazenda/unidade',[field('id','ID'),field('name','Nome'),field('registration','Inscrição/registro'),field('location','Localização')]),
    saveBreed:form('Cadastrar raça',[field('id','ID'),field('name','Nome'),field('species','Espécie')],v=>({id:clean(v.id),name:clean(v.name),species:clean(v.species)||'bovine'})),
    saveCategory:form('Cadastrar categoria',[field('id','ID'),field('name','Nome'),field('purpose','Finalidade','select',{options:[['beef','Corte'],['dairy','Leite'],['breeding','Reprodução']]})],v=>({id:clean(v.id),name:clean(v.name),purpose:v.purpose})),
    saveParty:form('Cadastrar contato/parte',[field('id','ID'),field('name','Nome / Razão social'),field('roles','Papéis','list'),field('document','CPF/CNPJ'),field('phone','Telefone'),field('email','E-mail'),field('notes','Observações')],v=>({id:clean(v.id),name:clean(v.name),roles:list(v.roles),document:clean(v.document)||null,phone:clean(v.phone)||null,email:clean(v.email)||null,notes:clean(v.notes)||null})),
    exportCollection:form('Exportar dados',[field('collection','Coleção','select',{options:[['cattle.farm-units','Fazendas / unidades'],['cattle.lots','Lotes'],['cattle.animals','Animais'],['cattle.breeds','Raças'],['cattle.categories','Categorias'],['cattle.parties','Contatos / partes'],['cattle.sanitary-protocols','Protocolos sanitários'],['cattle.events','Eventos'],['cattle.trades','Compras e vendas'],['cattle.finance','Financeiro'],['cattle.traceability','Rastreabilidade'],['cattle.inventory','Estoque e insumos'],['cattle.inventory-movements','Movimentações de estoque'],['cattle.pastures','Pastagens e áreas'],['cattle.pasture-occupancy','Ocupação de pastagens'],['cattle.pasture-assessments','Avaliações de pastagens'],['cattle.body-condition','Escore corporal'],['cattle.pasture-rotation-plan','Planos de rotação'],['cattle.nutrition','Nutrição'],['cattle.tasks','Agenda de manejo']]})],v=>({collection:v.collection})),
    validateImport:form('Validar importação JSON',[field('document','Documento JSON','textarea',{acceptFile:'.json'})],v=>({document:JSON.parse(v.document)})),
    importCollection:form('Importar JSON validado',[field('document','Documento JSON','textarea')],v=>({document:JSON.parse(v.document)}))
  }),
  iot:Object.freeze({
    saveDevice:form('Adicionar ou atualizar dispositivo',[field('id','ID do dispositivo'),field('name','Nome'),field('profileId','Tipo de integração','select',{options:iotProfiles}),field('stationId','Estação/curral'),field('farmId','Fazenda'),field('enabled','Ativar automaticamente','select',{options:[['true','Sim'],['false','Não']]}),field('port','Porta serial/USB'),field('baudRate','Baud rate','number'),field('delimiter','Delimitador serial'),field('url','URL MQTT'),field('topics','Tópicos MQTT','list'),field('baseUrl','URL HTTP local'),field('path','Caminho HTTP'),field('pollIntervalMs','Intervalo HTTP (ms)','number'),field('username','Usuário'),field('password','Senha','password'),field('token','Token','password')],iotDevice),
    removeDevice:form('Remover dispositivo',[field('id','ID do dispositivo')],v=>({id:clean(v.id)})),
    testDevice:form('Testar conexão',[field('id','ID do dispositivo')],v=>({id:clean(v.id)})),
    startDevice:form('Iniciar dispositivo',[field('id','ID do dispositivo')],v=>({id:clean(v.id)})),
    stopDevice:form('Parar dispositivo',[field('id','ID do dispositivo')],v=>({id:clean(v.id)})),
    bindRfid:form('Vincular RFID a animal',[field('tagId','Código RFID'),field('animalId','Animal','text',{refCollection:'animals'})],v=>({tagId:clean(v.tagId),animalId:clean(v.animalId)})),
    unbindRfid:form('Desvincular RFID',[field('tagId','Código RFID')],v=>({tagId:clean(v.tagId)})),
    simulateRfid:form('Simular leitura RFID',[field('deviceId','Dispositivo simulador'),field('tagId','Código RFID')],v=>({deviceId:clean(v.deviceId),tagId:clean(v.tagId)})),
    simulateWeight:form('Simular pesagem',[field('deviceId','Dispositivo simulador'),field('value','Peso','number',{step:'0.1'}),field('unit','Unidade','select',{options:[['kg','kg'],['g','g'],['lb','lb']]}),field('stable','Peso estável','select',{options:[['true','Sim'],['false','Não']]})],v=>({deviceId:clean(v.deviceId),value:num(v.value),unit:v.unit||'kg',stable:String(v.stable??'true')!=='false'}))
  }),
  settings:Object.freeze({
    backup:form('Criar backup',[field('id','Nome/ID do backup')],v=>v.id?{id:clean(v.id)}:{}),
    restore:form('Restaurar backup',[field('id','ID do backup')],v=>({id:clean(v.id)}))
  })
});

export const actionFormKeys=()=>Object.entries(ACTION_FORMS).flatMap(([screen,actions])=>Object.keys(actions).map(action=>`${screen}.${action}`));
export const getActionForm=(screenId,action)=>ACTION_FORMS[screenId]?.[action]??null;
