import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Icon} from './icons.jsx';
import {recordLocalTelemetry} from './p2-runtime.js';

export function StatusBanner({tone='info',children}){return <div className={`status ${tone}`} role={tone==='error'?'alert':'status'}>{children}</div>}

export function DesktopShell({brand,navigation,title,children,onLogout,notificationCount=0,onSearch=null,onNotifications=null}){
  const [mobileNavOpen,setMobileNavOpen]=useState(false);
  useEffect(()=>{const onKeyDown=event=>{if(event.key==='Escape')setMobileNavOpen(false)};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[]);
  return <div className="shell">
    <a className="skip-link" href="#main-content">Pular para o conteúdo principal</a>
    <button className={`sidebar-scrim ${mobileNavOpen?'show':''}`} type="button" aria-label="Fechar menu" onClick={()=>setMobileNavOpen(false)}/>
    <aside className="sidebar" data-testid="sidebar" data-open={String(mobileNavOpen)}><div className="brand">{brand}</div><nav aria-label="Navegação principal" onClick={()=>setMobileNavOpen(false)}>{navigation}</nav><div className="sidebar-foot"><Icon name="beef" size={18}/><span>Gestão local-first</span></div></aside>
    <div className="workspace"><header className="topbar"><button data-testid="mobile-nav-toggle" className="mobile-nav-toggle" type="button" aria-label="Abrir menu" aria-expanded={mobileNavOpen} onClick={()=>setMobileNavOpen(open=>!open)}><Icon name="menu" size={21}/></button><div className="topbar-title"><small>ArtiSys Pecuária</small><h1>{title}</h1></div><form className="global-search" onSubmit={e=>{e.preventDefault();const term=new FormData(e.currentTarget).get('term');if(term&&onSearch){recordLocalTelemetry('ui.search',{surface:'global'});onSearch(String(term))}}}><Icon name="search" size={18}/><input name="term" aria-label="Busca global" placeholder="Buscar animal, lote ou informação..."/></form><div className="topbar-actions"><button className="notification-button" type="button" aria-label={`${notificationCount} alertas`} onClick={()=>{recordLocalTelemetry('ui.notifications.open',{surface:'topbar'});onNotifications?.()}}><Icon name="bell" size={19}/>{notificationCount>0&&<span>{notificationCount>99?'99+':notificationCount}</span>}</button><div className="user-chip"><span className="avatar">AD</span><span><strong>Administrador</strong><small>Operação local</small></span></div><button className="ghost logout-button" onClick={()=>{recordLocalTelemetry('ui.logout',{surface:'topbar'});onLogout()}}>Sair</button></div></header><main id="main-content" tabIndex="-1" className="content">{children}</main></div>
  </div>;
}

const domainLabels={id:'ID',name:'Nome',tag:'Brinco',lotId:'Lote',lotName:'Lote',farmUnitId:'Fazenda / unidade',purpose:'Finalidade',status:'Status',complianceStatus:'Situação',sex:'Sexo',weightKg:'Peso (kg)',measuredAt:'Pesagem em',animalId:'Animal',relatedAnimalId:'Animal relacionado',kind:'Tipo',type:'Evento',occurredAt:'Data',performedAt:'Realizado em',nextDueAt:'Próxima data',withdrawalUntil:'Fim da carência',protocolId:'Protocolo',productItemId:'Produto / insumo',productBatch:'Lote/partida',activeIngredient:'Princípio ativo',dose:'Dose',unit:'Unidade',partyId:'Cliente / fornecedor',animalIds:'Animais',totalAmountMinor:'Valor líquido',amountMinor:'Valor',grossMinor:'Valor bruto',netMinor:'Valor líquido',liveArrobas:'@ peso vivo',carcassArrobas:'@ carcaça',carcassYieldPct:'Rendimento carcaça (%)',description:'Descrição',category:'Categoria',profileId:'Integração',stationId:'Estação / curral',farmId:'Fazenda',enabled:'Ativo',roles:'Papéis',document:'CPF/CNPJ',phone:'Telefone',email:'E-mail',quantity:'Saldo',minQuantity:'Estoque mínimo',expiresAt:'Validade',autonomyDays:'Autonomia (dias)',dailyKg:'Consumo/dia',headCount:'Cabeças'};
const humanize=key=>domainLabels[key]??String(key).replace(/([A-Z])/g,' $1').replace(/[-_]/g,' ').replace(/^./,letter=>letter.toUpperCase());
const moneyKeys=new Set(['amountMinor','totalAmountMinor','grossMinor','netMinor','costMinor','unitCostMinor','originalAmountMinor','openAmountMinor','pricePerCarcassArrobaMinor','deductionsMinor','freightMinor','commissionMinor','dailyCostMinor','costHeadDayMinor']);
const statusKeys=new Set(['status','complianceStatus','state']);
const statusClass=value=>String(value??'unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-');
const renderCell=(v,key)=>{
  if(v==null||v==='')return '—';
  if(moneyKeys.has(key)&&Number.isFinite(Number(v)))return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)/100);
  if(typeof v==='boolean')return v?'Sim':'Não';
  if(Array.isArray(v))return v.join(', ');
  if(typeof v==='object')return 'Detalhes';
  if(key==='carcassYieldPct'&&Number.isFinite(Number(v)))return `${Number(v).toFixed(2)}%`;
  if(key==='autonomyDays'&&Number.isFinite(Number(v)))return Number(v).toFixed(1);
  return String(v);
};
const searchableValue=row=>Object.values(row??{}).filter(value=>value==null||typeof value!=='object').join(' ').toLocaleLowerCase('pt-BR');
const safeDetailEntries=row=>Object.entries(row??{}).filter(([key])=>!['metadata','passwordHash','passwordSalt','tokenHash','password','token'].includes(key));

export const emptyStateByScreen={
  lots:{title:'Nenhum lote cadastrado',detail:'Crie o primeiro lote para organizar animais por finalidade e manejo.'},
  animals:{title:'Nenhum animal cadastrado',detail:'Cadastre um animal ou registre um nascimento para iniciar o histórico produtivo.'},
  weights:{title:'Nenhuma pesagem registrada',detail:'Use a pesagem rápida para criar o primeiro ponto do histórico de desempenho.'},
  sanitary:{title:'Nenhum manejo sanitário',detail:'Cadastre protocolos e aplicações para acompanhar próximas doses e carências.'},
  reproduction:{title:'Nenhum evento reprodutivo',detail:'Registre serviços, diagnósticos, partos ou desmames para formar os indicadores.'},
  trades:{title:'Nenhuma negociação',detail:'Compras e vendas registradas aparecerão aqui com seus fechamentos.'},
  finance:{title:'Nenhum lançamento financeiro',detail:'Custos, receitas, títulos e baixas aparecerão após as primeiras operações.'},
  reports:{title:'Nenhum documento emitido',detail:'Use o construtor acima para gerar o primeiro relatório ou emitir um documento.'},
  traceability:{title:'Nenhum registro de rastreabilidade',detail:'Adicione identificação oficial, GTA, SISBOV ou certificados para controle local.'},
  inventory:{title:'Nenhum insumo cadastrado',detail:'Cadastre medicamentos, vacinas, suplementos ou alimentos para controlar saldo e validade.'},
  pastures:{title:'Nenhuma área cadastrada',detail:'Cadastre pastagens e áreas para acompanhar capacidade, ocupação e rotação.'},
  nutrition:{title:'Nenhum plano nutricional',detail:'Crie um plano por lote para projetar consumo, autonomia de estoque e custo.'},
  tasks:{title:'Nenhum manejo agendado',detail:'Crie tarefas ou use o modo Campo para registrar operações locais.'},
  data:{title:'Nenhum cadastro nesta coleção',detail:'Comece pelas fazendas, raças, categorias e contatos usados no restante do sistema.'},
  iot:{title:'Nenhum dispositivo configurado',detail:'RFID e balanças são opcionais; adicione hardware apenas quando precisar.'},
  settings:{title:'Nenhum registro',detail:'As configurações locais aparecerão aqui quando aplicável.'}
};

export function DataTable({records=[],screenId=null,emptyState=null}){
  const [query,setQuery]=useState('');
  const [sortKey,setSortKey]=useState('');
  const [statusFilter,setStatusFilter]=useState('all');
  const [selected,setSelected]=useState(null);
  const detailCloseRef=useRef(null);
  useEffect(()=>{if(selected)setTimeout(()=>detailCloseRef.current?.focus(),0)},[selected]);
  const rows=useMemo(()=>records.map(v=>{const row=v?.payload??v;const settlement=row?.metadata?.settlement;if(!settlement)return row;return{id:row.id,type:row.type,partyId:row.partyId,carcassArrobas:settlement.carcassArrobas,carcassYieldPct:settlement.carcassYieldPct,grossMinor:settlement.grossMinor,netMinor:settlement.netMinor,totalAmountMinor:row.totalAmountMinor,...row}}),[records]);
  const columns=useMemo(()=>[...new Set(rows.flatMap(r=>Object.keys(r??{})))].filter(k=>!['metadata','passwordHash','passwordSalt','tokenHash'].includes(k)).slice(0,8),[rows]);
  const statusKey=useMemo(()=>columns.find(column=>statusKeys.has(column))??null,[columns]);
  const statuses=useMemo(()=>statusKey?[...new Set(rows.map(row=>row?.[statusKey]).filter(value=>value!==''&&value!=null).map(String))]:[],[rows,statusKey]);
  const visibleRows=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR');let filtered=term?rows.filter(row=>searchableValue(row).includes(term)):[...rows];if(statusKey&&statusFilter!=='all')filtered=filtered.filter(row=>String(row?.[statusKey])===statusFilter);if(!sortKey)return filtered;return filtered.sort((a,b)=>String(a?.[sortKey]??'').localeCompare(String(b?.[sortKey]??''),'pt-BR',{numeric:true,sensitivity:'base'}))},[rows,query,sortKey,statusKey,statusFilter]);
  const empty=emptyState??emptyStateByScreen[screenId]??{title:'Nenhum registro',detail:'Os dados aparecerão aqui quando forem cadastrados.'};
  if(!rows.length)return <div className="empty contextual"><strong>{empty.title}</strong><small>{empty.detail}</small></div>;
  return <div className="domain-table" data-testid="data-table">
    <div className="table-tools"><label><span className="sr-only">Filtrar registros</span><input data-testid="domain-table-search" type="search" placeholder="Filtrar registros..." value={query} onChange={event=>setQuery(event.target.value)}/></label>{statuses.length>1&&<label><span className="sr-only">Filtrar por status</span><select data-testid="status-filter" value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="all">Todos os status</option>{statuses.map(status=><option value={status} key={status}>{status}</option>)}</select></label>}<label><span className="sr-only">Ordenar por</span><select data-testid="domain-table-sort" value={sortKey} onChange={event=>setSortKey(event.target.value)}><option value="">Ordem original</option>{columns.map(column=><option value={column} key={column}>Ordenar por {humanize(column)}</option>)}</select></label><small>{visibleRows.length} de {rows.length}</small></div>
    <div className="table-wrap"><table className="responsive-table"><thead><tr>{columns.map(c=><th key={c}>{humanize(c)}</th>)}<th><span className="sr-only">Detalhes</span></th></tr></thead><tbody>{visibleRows.map((row,i)=><tr key={row.id??i}>{columns.map(c=><td key={c} data-label={humanize(c)}>{statusKeys.has(c)?<span className={`status-chip status-chip-${statusClass(row[c])}`}>{renderCell(row[c],c)}</span>:renderCell(row[c],c)}</td>)}<td className="table-row-action" data-label="Detalhes"><button type="button" className="ghost" onClick={()=>{recordLocalTelemetry('ui.record.detail',{surface:screenId??'table'});setSelected(row)}}>Ver detalhes</button></td></tr>)}</tbody></table></div>
    {selected&&<aside className="record-detail-drawer" data-testid="record-detail-drawer" role="dialog" aria-modal="true" aria-label="Detalhes do registro" onKeyDown={event=>{if(event.key==='Escape')setSelected(null)}}><header><div><span className="eyebrow">Detalhes</span><h2>{selected.name??selected.tag??selected.title??selected.id??'Registro'}</h2></div><button ref={detailCloseRef} type="button" className="ghost" onClick={()=>setSelected(null)}>Fechar detalhes</button></header><div className="record-detail-grid">{safeDetailEntries(selected).map(([key,value])=><div key={key}><span>{humanize(key)}</span><strong>{renderCell(value,key)}</strong></div>)}</div></aside>}
  </div>;
}

const workspaceDescriptions={lots:'Organize grupos de manejo e acompanhe a distribuição do rebanho.',animals:'Consulte identificação, lote, finalidade e ciclo de vida dos animais.',weights:'Registre pesagens e preserve o histórico individual de desempenho.',sanitary:'Centralize protocolos, aplicações, estoque, custos e períodos de carência sanitária.',reproduction:'Acompanhe cobertura, diagnóstico, perdas, parto, desmame e indicadores reprodutivos.',trades:'Registre compras e vendas com fechamento por peso vivo, rendimento e arroba de carcaça.',finance:'Gerencie resultado por lote, contas a pagar e receber, caixa, previsões e conciliação local.',reports:'Emita relatórios zootécnicos e documentos operacionais.',traceability:'Centralize identificação oficial, GTA, SISBOV, certificados e histórico documental dos animais.',inventory:'Acompanhe saldo, lote/partida, validade, estoque mínimo, custo e movimentações dos insumos.',pastures:'Visualize ocupação, capacidade, descanso, avaliações de forragem e rotação planejada x realizada.',nutrition:'Planeje alimentação por lote, acompanhe consumo e faça baixa transacional dos insumos.',tasks:'Organize a agenda e execute manejos no campo com operação touch-first e sincronização local segura.',data:'Gerencie fazendas, raças, categorias, contatos e faça exportação, validação e importação segura de dados.',iot:'Configure integrações locais com RFID, balanças e dispositivos compatíveis.',settings:'Administre backup, restauração e preferências locais do sistema.'};

const intentLabels={
  'lots.save':'Novo lote','lots.remove':'Excluir lote','animals.save':'Novo animal','animals.recordMilk':'Registrar produção de leite','animals.move':'Mover animal','animals.lifecycle':'Registrar ciclo de vida','animals.batchMove':'Mover animais em lote','animals.batchLifecycle':'Registrar baixa coletiva','animals.recordBodyCondition':'Registrar escore corporal','animals.registerBirth':'Registrar nascimento','weights.record':'Registrar pesagem','sanitary.saveProtocol':'Novo protocolo','sanitary.record':'Registrar manejo sanitário','sanitary.batchRecord':'Registrar manejo sanitário coletivo','reproduction.record':'Registrar evento reprodutivo','reproduction.batchRecord':'Registrar evento reprodutivo coletivo','trades.create':'Registrar negociação','finance.addCost':'Registrar custo','finance.fromTrade':'Gerar lançamento da negociação','finance.saveAccount':'Nova conta ou caixa','finance.saveCategory':'Nova categoria financeira','finance.saveTitle':'Novo título','finance.cancelTitle':'Cancelar título','finance.settleTitle':'Registrar baixa','finance.reverseSettlement':'Estornar baixa','finance.importStatement':'Importar extrato','finance.reconcileStatement':'Conciliar extrato','finance.importInvoiceXml':'Ler XML de NF-e','reports.csv':'Gerar CSV','reports.pdf':'Gerar PDF','reports.issue':'Emitir relatório','traceability.save':'Novo registro de rastreabilidade','traceability.remove':'Excluir registro','inventory.save':'Novo insumo','inventory.adjust':'Registrar movimentação','pastures.save':'Nova pastagem ou área','pastures.enterLot':'Registrar entrada do lote','pastures.leaveLot':'Registrar saída do lote','pastures.recordAssessment':'Registrar avaliação de pastagem','pastures.saveRotationPlan':'Novo plano de rotação','nutrition.save':'Novo plano nutricional','nutrition.consume':'Registrar consumo','tasks.save':'Novo manejo ou tarefa','tasks.complete':'Concluir tarefa','data.saveFarmUnit':'Nova fazenda','data.saveBreed':'Nova raça','data.saveCategory':'Nova categoria','data.saveParty':'Novo contato','data.exportCollection':'Exportar coleção','data.validateImport':'Validar importação','data.importCollection':'Importar dados','iot.saveDevice':'Adicionar dispositivo','iot.removeDevice':'Remover dispositivo','iot.testDevice':'Testar dispositivo','iot.startDevice':'Iniciar dispositivo','iot.stopDevice':'Parar dispositivo','iot.bindRfid':'Vincular RFID','iot.unbindRfid':'Desvincular RFID','iot.simulateRfid':'Simular RFID','iot.simulateWeight':'Simular balança','settings.backup':'Criar backup','settings.restore':'Restaurar backup'
};
export const intentLabel=(screenId,name,fallback)=>intentLabels[`${screenId}.${name}`]??fallback??humanize(name);
const submitIntentLabel=actionKey=>{
  if(!actionKey)return'Concluir ação';
  if(/remove|cancel/i.test(actionKey))return'Confirmar exclusão';
  if(/reverse/i.test(actionKey))return'Confirmar estorno';
  if(/restore/i.test(actionKey))return'Confirmar restauração';
  if(/import/i.test(actionKey))return'Importar';
  if(/record|consume|settle|adjust|create|fromTrade/i.test(actionKey))return'Registrar';
  if(/save/i.test(actionKey))return'Cadastrar';
  if(/complete/i.test(actionKey))return'Concluir';
  if(/export/i.test(actionKey))return'Exportar';
  if(/validate/i.test(actionKey))return'Validar';
  if(/test/i.test(actionKey))return'Testar';
  return'Concluir ação';
};

export function WorkspaceScreen({screenId,screen,icon,records,onAction,allowedActions=null,secondaryRecords=null,secondaryTitle=null}){return <section className="workspace-screen panel" data-testid="workspace-screen"><div className="workspace-screen-heading"><div className="workspace-screen-intro"><span className="workspace-screen-icon" data-testid="workspace-screen-icon"><Icon name={icon} size={21}/></span><div><span className="eyebrow">Operação</span><h2>{screen?.title}</h2><p>{workspaceDescriptions[screenId]??'Gerencie os registros desta área.'}</p></div></div><div className="actions">{Object.entries(screen?.actionDefinitions??{}).filter(([name])=>!allowedActions||allowedActions.includes(name)).map(([name,definition])=><button key={name} data-testid={`action-${screenId}-${name}`} onClick={()=>{recordLocalTelemetry('ui.action.open',{surface:screenId,action:name});onAction(name)}}>{intentLabel(screenId,name,definition.label??name)}</button>)}</div></div><DataTable records={records} screenId={screenId}/>{secondaryRecords&&<section data-testid={`secondary-${screenId}`}><div className="workspace-screen-heading"><div><span className="eyebrow">Histórico</span><h3>{secondaryTitle}</h3></div></div><DataTable records={secondaryRecords} screenId={screenId}/></section>}</section>}

const technicalFieldsByAction={'finance.saveTitle':new Set(['id']),'finance.settleTitle':new Set(['id','operationId']),'finance.reverseSettlement':new Set(['id','operationId']),'finance.reconcileStatement':new Set(['operationId'])};
const technicalPrefixByAction={'finance.saveTitle':[['id','title']],'finance.settleTitle':[['id','settlement'],['operationId','settlement-op']],'finance.reverseSettlement':[['id','reversal'],['operationId','reversal-op']],'finance.reconcileStatement':[['operationId','reconciliation-op']]};
const isMoneyField=field=>field.moneyMinor===true||/\(centavos\)/i.test(field.label??'');
const moneyLabel=label=>String(label).replace(/\s*\(centavos\)/i,' (R$)');
const moneyToMinor=value=>{if(value===''||value==null)return undefined;let raw=String(value).trim().replace(/^R\$\s*/i,'').replace(/\s+/g,'');if(raw.includes(','))raw=raw.replace(/\./g,'').replace(',','.');const parsed=Number(raw);if(!Number.isFinite(parsed))throw new TypeError('Informe um valor monetário válido.');return Math.round(parsed*100)};
const technicalId=prefix=>`${prefix}-${crypto.randomUUID()}`;

export function ActionDialog({open,definition,actionKey,initialValues={},onClose,onSubmit,busy=false,references={}}){
  const [values,setValues]=useState({});
  const dialogRef=useRef(null),returnFocusRef=useRef(null);
  useEffect(()=>{if(open)setValues({...definition?.defaults,...initialValues})},[open,definition,initialValues]);
  useEffect(()=>{
    if(!open||!definition)return;
    returnFocusRef.current=document.activeElement;
    const focusTimer=setTimeout(()=>dialogRef.current?.querySelector('[data-testid^="field-"],input,select,textarea,button')?.focus(),0);
    const onKeyDown=event=>{
      if(event.key==='Escape'){event.preventDefault();onClose();return;}
      if(event.key!=='Tab'||!dialogRef.current)return;
      const focusable=[...dialogRef.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')].filter(element=>element.offsetParent!==null);
      if(!focusable.length)return;
      const first=focusable[0],last=focusable.at(-1);
      if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}
      else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}
    };
    document.addEventListener('keydown',onKeyDown);
    return()=>{clearTimeout(focusTimer);document.removeEventListener('keydown',onKeyDown);setTimeout(()=>returnFocusRef.current?.focus?.(),0)};
  },[open,definition,onClose]);
  if(!open||!definition)return null;
  const change=(name,value)=>setValues(current=>({...current,[name]:value}));
  const hidden=technicalFieldsByAction[actionKey]??new Set();
  const visibleFields=definition.fields.filter(field=>!hidden.has(field.name));
  const submit=async e=>{e.preventDefault();const prepared={...values};for(const field of definition.fields)if(isMoneyField(field)&&prepared[field.name]!==''&&prepared[field.name]!=null)prepared[field.name]=moneyToMinor(prepared[field.name]);for(const [name,prefix] of technicalPrefixByAction[actionKey]??[])if(!prepared[name])prepared[name]=technicalId(prefix);await onSubmit(definition.normalize(prepared));recordLocalTelemetry('ui.action.submit',{action:actionKey??'unknown'})};
  return <div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section ref={dialogRef} className="dialog" role="dialog" aria-modal="true" aria-label={definition.title}><header><div><small>Ação</small><h2>{definition.title}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar">×</button></header><form onSubmit={submit}><div className="form-grid">{visibleFields.map(f=><label key={f.name}><span>{isMoneyField(f)?moneyLabel(f.label):f.label}</span>{f.acceptFile?<><input type="file" accept={f.acceptFile} onChange={async e=>{const file=e.target.files?.[0];if(file)change(f.name,await file.text())}}/><textarea data-testid={`field-${f.name}`} rows="5" value={values[f.name]??''} onChange={e=>change(f.name,e.target.value)}/></>:f.refCollection&&f.type==='list'?<select multiple data-testid={`field-${f.name}`} value={Array.isArray(values[f.name])?values[f.name]:[]} onChange={e=>change(f.name,[...e.target.selectedOptions].map(o=>o.value))}>{(references[f.refCollection]??[]).map(item=><option value={item.id} key={item.id}>{item.tag??item.name??item.officialId??item.id}</option>)}</select>:f.refCollection?<select data-testid={`field-${f.name}`} value={values[f.name]??''} onChange={e=>change(f.name,e.target.value)}><option value="">Selecione</option>{(references[f.refCollection]??[]).map(item=><option value={item.id} key={item.id}>{item.tag??item.name??item.officialId??item.id}</option>)}</select>:f.type==='select'?<select data-testid={`field-${f.name}`} value={values[f.name]??''} onChange={e=>change(f.name,e.target.value)}><option value="">Selecione</option>{(f.options??[]).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:f.type==='textarea'||f.type==='list'?<textarea data-testid={`field-${f.name}`} rows={f.type==='list'?3:5} placeholder={f.placeholder} value={values[f.name]??''} onChange={e=>change(f.name,e.target.value)}/>:<input data-testid={`field-${f.name}`} type={isMoneyField(f)?'text':f.type} inputMode={isMoneyField(f)?'decimal':undefined} step={f.step} placeholder={isMoneyField(f)?'0,00':f.placeholder} value={values[f.name]??''} onChange={e=>change(f.name,e.target.value)}/>}</label>)}</div><footer><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button data-testid="action-submit" className="primary" disabled={busy}>{busy?'Executando…':submitIntentLabel(actionKey)}</button></footer></form></section></div>;
}

export function AnimalDetail({detail,onClose}){if(!detail?.animal)return null;const a=detail.animal;const facts=[['Brinco',a.tag],['Identificação oficial',a.officialId],['RFID',a.rfid],['Lote',a.lotId],['Fazenda',a.farmUnitId],['Raça',a.breedId],['Categoria',a.categoryId],['Nascimento',a.birthDate],['Mãe',a.damId],['Pai',a.sireId],['Peso atual',a.latestWeightKg==null?null:`${a.latestWeightKg} kg`],['GMD',a.dailyGainKg==null?null:`${Number(a.dailyGainKg).toFixed(3)} kg/dia`]];return <section className="panel animal-detail" data-testid="animal-360"><div className="panel-heading"><div><span className="eyebrow">Ficha 360º</span><h2>{a.name||a.tag}</h2><p>Histórico consolidado do animal.</p></div><button className="ghost" onClick={onClose}>Fechar</button></div><div className="animal-facts">{facts.map(([k,v])=><div key={k}><span>{k}</span><strong>{v||'—'}</strong></div>)}</div><h3>Linha do tempo</h3><div className="activity-list">{(detail.timeline??[]).map((x,i)=><div className="activity-row" key={i}><span className="activity-copy"><strong>{x.title}</strong><small>{x.detail||'Registro'}</small></span><time>{x.occurredAt?new Date(x.occurredAt).toLocaleDateString('pt-BR'):'—'}</time></div>)}</div></section>}

export function CorralFlow({animals=[],onRecord}){const [animalId,setAnimalId]=useState('');const [weight,setWeight]=useState('');const animal=animals.map(x=>x.payload??x).find(x=>x.id===animalId);const previous=animal?.weights?.at(-1)?.weightKg??null;return <section className="panel" data-testid="corral-flow"><div className="panel-heading"><div><span className="eyebrow">Curral</span><h2>Pesagem rápida</h2><p>Identifique, confira o histórico e registre o próximo peso.</p></div></div><div className="form-grid"><label><span>Animal</span><select value={animalId} onChange={e=>setAnimalId(e.target.value)}><option value="">Selecione</option>{animals.map(r=>{const a=r.payload??r;return <option key={a.id} value={a.id}>{a.tag??a.name??a.id}</option>})}</select></label><label><span>Novo peso (kg)</span><input type="number" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></label></div>{animal&&<div className="mini-metrics"><div><span>Peso anterior</span><strong>{previous??'—'} kg</strong></div><div><span>GMD atual</span><strong>{animal.dailyGainKg==null?'—':`${Number(animal.dailyGainKg).toFixed(3)} kg/dia`}</strong></div><div><span>Diferença</span><strong>{previous!=null&&weight?`${(Number(weight)-previous).toFixed(1)} kg`:'—'}</strong></div></div>}<div className="actions"><button className="primary" disabled={!animalId||!Number(weight)} onClick={()=>onRecord({id:animalId,weightKg:Number(weight),measuredAt:new Date().toISOString()}).then(()=>{setWeight('');setAnimalId('')})}>Registrar e próximo</button></div></section>}

export function FinanceMetrics({metrics}){if(!metrics)return null;const money=v=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)/100);return <section className="panel" data-testid="finance-metrics"><div className="panel-heading"><div><span className="eyebrow">Economia produtiva</span><h2>Indicadores do lote</h2></div></div><div className="stat-grid"><article><span>Custo/cabeça</span><strong>{money(metrics.costPerHeadMinor)}</strong></article><article><span>Custo/kg ganho</span><strong>{money(metrics.costPerKgGainMinor)}</strong></article><article><span>Custo/@ peso vivo</span><strong>{money(metrics.costPerLiveArrobaMinor??metrics.costPerArrobaMinor)}</strong></article><article><span>Margem</span><strong>{money(metrics.marginMinor)}</strong></article></div></section>}

const percent=value=>value==null?'—':`${Number(value).toFixed(1)}%`;
export function ReproductionSummary({records=[],metrics=null}){const rows=records.map(r=>r.payload??r);const upcoming=rows.filter(r=>r.metadata?.expectedCalvingAt);return <section className="panel" data-testid="reproduction-summary"><div className="panel-heading"><div><span className="eyebrow">Gestão reprodutiva</span><h2>Indicadores e previsões</h2><p>{upcoming.length} parto(s) com previsão registrada.</p></div></div>{metrics&&<div className="stat-grid" data-testid="reproduction-metrics"><article><span>Taxa de serviço</span><strong>{percent(metrics.serviceRatePct)}</strong></article><article><span>Taxa de concepção</span><strong>{percent(metrics.conceptionRatePct)}</strong></article><article><span>Taxa de prenhez</span><strong>{percent(metrics.pregnancyRatePct)}</strong></article><article><span>Perda gestacional</span><strong>{percent(metrics.pregnancyLossRatePct)}</strong></article><article><span>Taxa de parto</span><strong>{percent(metrics.calvingRatePct)}</strong></article><article><span>Taxa de desmame</span><strong>{percent(metrics.weaningRatePct)}</strong></article></div>}<DataTable records={upcoming.map(r=>({animalId:r.animalId,type:r.type,expectedCalvingAt:r.metadata.expectedCalvingAt,result:r.metadata.result??''}))} screenId="reproduction"/></section>}
