import React from 'react';

const statusLabel={available:'Disponível',occupied:'Ocupado',resting:'Descanso',unavailable:'Indisponível'};
const fmt=value=>value==null?'Sem dados':String(value);
const polygonPoints=polygon=>(polygon??[]).map(point=>`${Number(point.x).toFixed(1)},${Number(point.y).toFixed(1)}`).join(' ');
const hoursBetween=(planned,actual)=>{const a=Date.parse(planned),b=Date.parse(actual);return Number.isFinite(a)&&Number.isFinite(b)?Number(((b-a)/3600000).toFixed(1)):null};

function PastureMap({pastures=[]}){
  return <section className="panel" data-testid="pasture-local-map"><div className="panel-heading"><div><span className="eyebrow">Sem serviço de mapas</span><h2>Mapa esquemático local</h2><p>Desenho salvo no próprio banco. A operação não depende de Google Maps, internet ou assinatura.</p></div></div><div className="pasture-map-grid">{pastures.map((pasture,index)=><article className="pasture-map-card" key={pasture.id}><svg viewBox="0 0 100 100" role="img" aria-label={`Área ${pasture.name??pasture.id}`}><rect x="2" y="2" width="96" height="96" rx="8" fill="none" stroke="currentColor" strokeOpacity=".18"/>{pasture.polygon?.length>=3?<polygon points={polygonPoints(pasture.polygon)} fill="currentColor" fillOpacity=".12" stroke="currentColor" strokeWidth="1.5"/>:<rect x={10+(index%3)*4} y={12+(index%4)*3} width="72" height="62" rx="10" fill="currentColor" fillOpacity=".08" stroke="currentColor" strokeDasharray="4 3"/>}</svg><div><strong>{pasture.name??pasture.id}</strong><span className="muted">{statusLabel[pasture.operationalStatus]??pasture.operationalStatus} · {fmt(pasture.areaHa)} ha</span></div></article>)}</div></section>;
}

export function PastureManagementWorkspace({data}){
  const management=data??{},pastures=management.pastures??[],rotationPlans=management.rotationPlans??[],bodyCondition=management.bodyCondition??[],occupancy=management.occupancy??[];
  return <div className="pasture-management" data-testid="pasture-management">
    <section className="panel" data-testid="pasture-status-cards"><div className="panel-heading"><div><span className="eyebrow">Estado operacional</span><h2>Pastagens</h2><p>Capacidade, ocupação e descanso derivados do histórico local.</p></div></div><div className="data-cards">{pastures.map(pasture=><article className="data-card" key={pasture.id}><strong>{pasture.name??pasture.id}</strong><span>Status: {statusLabel[pasture.operationalStatus]??pasture.operationalStatus}</span><span>Área: {fmt(pasture.areaHa)} ha</span><span>Capacidade: {pasture.capacityAu==null?'Sem dados':`${pasture.capacityAu} UA`}</span><span>Descanso: {pasture.restDays==null?'Sem dados':`${pasture.restDays} dia(s)`}</span></article>)}</div></section>
    <PastureMap pastures={pastures}/>
    <section className="panel" data-testid="pasture-assessments"><div className="panel-heading"><div><span className="eyebrow">Medição de campo</span><h2>Avaliações de pastagem</h2><p>Altura, massa, cobertura e escore vêm de observações registradas; valores ausentes aparecem como Sem dados.</p></div></div><div data-testid="pasture-condition">{pastures.length?<div className="data-cards">{pastures.map(pasture=>{const latestAssessment=pasture.latestAssessment;return <article className="data-card" key={pasture.id}><strong>{pasture.name??pasture.id}</strong><span>Escore: {fmt(latestAssessment?.score)}</span><span>Altura: {latestAssessment?.heightCm==null?'Sem dados':`${latestAssessment.heightCm} cm`}</span><span>Massa: {latestAssessment?.forageMassKgHa==null?'Sem dados':`${latestAssessment.forageMassKgHa} kg/ha`}</span><span>Cobertura: {latestAssessment?.groundCoverPct==null?'Sem dados':`${latestAssessment.groundCoverPct}%`}</span></article>})}</div>:<p className="muted">Sem dados de avaliações de pastagem.</p>}</div></section>
    <section className="panel" data-testid="pasture-rotation-plan"><div className="panel-heading"><div><span className="eyebrow">Planejamento local</span><h2>Rotação planejada</h2><p>{rotationPlans.length} plano(s) local(is).</p></div></div><div data-testid="pasture-rotations">{rotationPlans.length?<div className="data-cards">{rotationPlans.map(plan=><article className="data-card" key={plan.id}><strong>{plan.id}</strong><span>Pasto: {plan.pastureId}</span><span>Lote: {plan.lotId}</span><span>Entrada: {plan.plannedEnterAt}</span><span>Saída: {plan.plannedLeaveAt??'Sem dados'}</span><span>Status: {plan.status}</span></article>)}</div>:<p className="muted">Nenhuma rotação planejada.</p>}</div></section>
    <section className="panel" data-testid="pasture-plan-vs-actual"><div className="panel-heading"><div><span className="eyebrow">Planejado x realizado</span><h2>Execução da rotação</h2><p>O plano permanece separado do histórico real de ocupação.</p></div></div>{rotationPlans.length?<div className="data-cards">{rotationPlans.map(plan=>{const actual=occupancy.filter(item=>item.pastureId===plan.pastureId&&item.lotId===plan.lotId).slice().sort((a,b)=>Math.abs(Date.parse(a.enteredAt)-Date.parse(plan.plannedEnterAt))-Math.abs(Date.parse(b.enteredAt)-Date.parse(plan.plannedEnterAt)))[0]??null;const enterVariance=hoursBetween(plan.plannedEnterAt,actual?.enteredAt),leaveVariance=hoursBetween(plan.plannedLeaveAt,actual?.leftAt);return <article className="data-card" key={`${plan.id}:actual`}><strong>{plan.id}</strong><span>Entrada planejada: {plan.plannedEnterAt}</span><span>Entrada real: {actual?.enteredAt??'Sem dados'}</span><span>Variação entrada: {enterVariance==null?'Sem dados':`${enterVariance} h`}</span><span>Saída planejada: {plan.plannedLeaveAt??'Sem dados'}</span><span>Saída real: {actual?.leftAt??'Sem dados'}</span><span>Variação saída: {leaveVariance==null?'Sem dados':`${leaveVariance} h`}</span></article>})}</div>:<p className="muted">Sem dados de planejamento para comparar.</p>}</section>
    <section className="panel" data-testid="pasture-body-condition"><div className="panel-heading"><div><span className="eyebrow">Observação zootécnica</span><h2>Escore corporal</h2><p>{bodyCondition.length} observação(ões) registrada(s).</p></div></div>{bodyCondition.length?<div className="data-cards">{bodyCondition.slice().sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,12).map(item=><article className="data-card" key={item.id}><strong>{item.animalId}</strong><span>Escore: {item.score}</span><span>Escala: {item.scaleMin}–{item.scaleMax}</span><span>{item.occurredAt}</span></article>)}</div>:<p className="muted">Sem escores corporais registrados.</p>}</section>
  </div>;
}
