import React from 'react';

const statusLabel={available:'Disponível',occupied:'Ocupado',resting:'Descanso',unavailable:'Indisponível'};
const fmt=value=>value==null?'—':String(value);
const polygonPoints=polygon=>(polygon??[]).map(point=>`${Number(point.x).toFixed(1)},${Number(point.y).toFixed(1)}`).join(' ');

function PastureMap({pastures=[]}){
  return <section className="panel" data-testid="pasture-local-map"><div className="panel-heading"><div><span className="eyebrow">Sem serviço de mapas</span><h2>Mapa esquemático local</h2><p>Desenho salvo no próprio banco. A operação não depende de Google Maps, internet ou assinatura.</p></div></div><div className="pasture-map-grid">{pastures.map((pasture,index)=><article className="pasture-map-card" key={pasture.id}><svg viewBox="0 0 100 100" role="img" aria-label={`Área ${pasture.name??pasture.id}`}><rect x="2" y="2" width="96" height="96" rx="8" fill="none" stroke="currentColor" strokeOpacity=".18"/>{pasture.polygon?.length>=3?<polygon points={polygonPoints(pasture.polygon)} fill="currentColor" fillOpacity=".12" stroke="currentColor" strokeWidth="1.5"/>:<rect x={10+(index%3)*4} y={12+(index%4)*3} width="72" height="62" rx="10" fill="currentColor" fillOpacity=".08" stroke="currentColor" strokeDasharray="4 3"/>}</svg><div><strong>{pasture.name??pasture.id}</strong><span className="muted">{statusLabel[pasture.operationalStatus]??pasture.operationalStatus} · {fmt(pasture.areaHa)} ha</span></div></article>)}</div></section>;
}

export function PastureManagementWorkspace({data}){
  const management=data??{},pastures=management.pastures??[],rotationPlans=management.rotationPlans??[],bodyCondition=management.bodyCondition??[];
  return <div className="pasture-management"><PastureMap pastures={pastures}/><section className="panel" data-testid="pasture-condition"><div className="panel-heading"><div><span className="eyebrow">Medição de campo</span><h2>Condição medida</h2><p>Altura, massa, cobertura e escore vêm de observações registradas; valores ausentes continuam ausentes.</p></div></div><div className="data-cards">{pastures.map(pasture=>{const latestAssessment=pasture.latestAssessment;return <article className="data-card" key={pasture.id}><strong>{pasture.name??pasture.id}</strong><span>Status: {statusLabel[pasture.operationalStatus]??pasture.operationalStatus}</span><span>Escore: {fmt(latestAssessment?.score)}</span><span>Altura: {latestAssessment?.heightCm==null?'—':`${latestAssessment.heightCm} cm`}</span><span>Massa: {latestAssessment?.forageMassKgHa==null?'—':`${latestAssessment.forageMassKgHa} kg/ha`}</span><span>Cobertura: {latestAssessment?.groundCoverPct==null?'—':`${latestAssessment.groundCoverPct}%`}</span></article>})}</div></section><section className="panel" data-testid="pasture-rotations"><div className="panel-heading"><div><span className="eyebrow">Planejado x executado</span><h2>Rotação planejada</h2><p>{rotationPlans.length} plano(s) local(is).</p></div></div>{rotationPlans.length?<div className="data-cards">{rotationPlans.map(plan=><article className="data-card" key={plan.id}><strong>{plan.id}</strong><span>Pasto: {plan.pastureId}</span><span>Lote: {plan.lotId}</span><span>Entrada: {plan.plannedEnterAt}</span><span>Saída: {plan.plannedLeaveAt??'—'}</span><span>Status: {plan.status}</span></article>)}</div>:<p className="muted">Nenhuma rotação planejada.</p>}</section><section className="panel" data-testid="pasture-body-condition"><div className="panel-heading"><div><span className="eyebrow">Observação zootécnica</span><h2>Escore corporal</h2><p>{bodyCondition.length} observação(ões) registrada(s).</p></div></div>{bodyCondition.length?<div className="data-cards">{bodyCondition.slice().sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,12).map(item=><article className="data-card" key={item.id}><strong>{item.animalId}</strong><span>Escore: {item.score}</span><span>Escala: {item.scaleMin}–{item.scaleMax}</span><span>{item.occurredAt}</span></article>)}</div>:<p className="muted">Sem escores corporais registrados.</p>}</section></div>;
}
